import type { WalletMeta, WalletId } from "../types/";
import { formatDeepLink } from "./deepLink";

export const POPULAR_ORDER: WalletId[] = [
  "metamask",
  "coinbase",
  "walletconnect",
  "rainbow",
  "rabby",
  "okx",
  "brave",
  "zerion",
  "taho",
  "trust",
  "bitget",
  "phantom-evm",
  "imtoken",
  "safe",
  "kucoin",
];

export const WALLETS: WalletMeta[] = [
  {
    id: "metamask",
    name: "MetaMask",
    category: "injected",
    logo: "/assets/wallets/metamask.svg",
    emoji: "🦊",
    homepage: "https://metamask.io/",
    chromeWebStore:
      "https://chromewebstore.google.com/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn",
    detectFlags: ["isMetaMask"],
    deepLink: (url) => formatDeepLink("metamask", url) ?? "",
  },
  {
    id: "rabby",
    name: "Rabby",
    category: "injected",
    logo: "/assets/wallets/rabby.svg",
    emoji: "🐰",
    homepage: "https://rabby.io/",
    chromeWebStore:
      "https://chromewebstore.google.com/detail/rabby/acmacodkjbdgmoleebolmdjonilkdbch",
    detectFlags: ["isRabby"],
  },
  {
    id: "coinbase",
    name: "Coinbase Wallet",
    category: "app",
    logo: "/assets/wallets/coinbase.svg",
    emoji: "🟦",
    homepage: "https://www.coinbase.com/wallet",
    detectFlags: ["isCoinbaseWallet"],
    deepLink: (url) => formatDeepLink("coinbase", url) ?? "",
  },
  {
    id: "walletconnect",
    name: "WalletConnect",
    category: "walletconnect",
    logo: "/assets/wallets/walletconnect.svg",
    emoji: "🪝",
    homepage: "https://walletconnect.com/",
  },
  {
    id: "rainbow",
    name: "Rainbow",
    category: "app",
    logo: "/assets/wallets/rainbow.svg",
    emoji: "🌈",
    homepage: "https://rainbow.me/",
    deepLink: (url) => formatDeepLink("rainbow", url) ?? "",
  },
  {
    id: "okx",
    name: "OKX",
    category: "injected",
    logo: "/assets/wallets/okx.svg",
    emoji: "⬛",
    homepage: "https://www.okx.com/web3",
    detectFlags: ["isOkxWallet"],
  },
  {
    id: "brave",
    name: "Brave Wallet",
    category: "injected",
    logo: "/assets/wallets/brave.svg",
    emoji: "🦁",
    homepage: "https://brave.com/wallet/",
    detectFlags: ["isBraveWallet"],
  },
  {
    id: "zerion",
    name: "Zerion",
    category: "app",
    logo: "/assets/wallets/zerion.svg",
    emoji: "🧿",
    homepage: "https://zerion.io/wallet/",
  },
  {
    id: "taho",
    name: "Taho",
    category: "injected",
    logo: "/assets/wallets/taho.svg",
    emoji: "🟪",
    homepage: "https://taho.xyz/",
    detectFlags: ["isTally"],
  },
  {
    id: "trust",
    name: "Trust Wallet",
    category: "app",
    logo: "/assets/wallets/trust.svg",
    emoji: "🛡️",
    homepage: "https://trustwallet.com/",
  },
  {
    id: "bitget",
    name: "Bitget Wallet",
    category: "app",
    logo: "/assets/wallets/bitget.svg",
    emoji: "🟩",
    homepage: "https://web3.bitget.com/",
  },
  {
    id: "phantom-evm",
    name: "Phantom (EVM)",
    category: "app",
    logo: "/assets/wallets/phantom.svg",
    emoji: "👻",
    homepage: "https://phantom.app/",
  },
  {
    id: "imtoken",
    name: "imToken",
    category: "app",
    logo: "/assets/wallets/imtoken.svg",
    emoji: "💠",
    homepage: "https://token.im/",
  },
  {
    id: "safe",
    name: "Safe",
    category: "app",
    logo: "/assets/wallets/safe.svg",
    emoji: "🟩",
    homepage: "https://safe.global/",
  },
  {
    id: "kucoin",
    name: "KuCoin Wallet",
    category: "app",
    logo: "/assets/wallets/kucoin.svg",
    emoji: "🟦",
    homepage: "https://www.kucoin.com/",
  },
];
