import type { WalletMeta, WalletId } from "../types/";
import { formatDeepLink } from "./deepLink";
import { ASSETS_BASE_URL } from "../constants";

export const POPULAR_ORDER: WalletId[] = [
  "rabby",
  "metamask",
  "walletconnect",
  "rainbow",
  "phantom-evm",
  "phantom-solana",
  "solflare",
  "okx",
  "brave",
  "coinbase",
  "zerion",
  "taho",
  "trust",
  "bitget",
  "backpack",
  "imtoken",
  "safe",
  "kucoin",
];

export const WALLETS: WalletMeta[] = [
  {
    id: "metamask",
    name: "MetaMask",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/metamask.svg`,
    emoji: "🦊",
    homepage: "https://metamask.io/",
    chromeWebStore:
      "https://chromewebstore.google.com/detail/metamask/nkbihfbeogaeaoehlefnkodbefgpgknn",
    detectFlags: ["isMetaMask"],
    deepLink: (url) => formatDeepLink("metamask", url) ?? "",
  },
  {
    id: "coinbase",
    name: "Coinbase Wallet",
    category: "app",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/coinbase.svg`,
    emoji: "🟦",
    homepage: "https://www.coinbase.com/wallet",
    detectFlags: ["isCoinbaseWallet"],
    deepLink: (url) => formatDeepLink("coinbase", url) ?? "",
  },
  {
    id: "walletconnect",
    name: "WalletConnect",
    category: "walletconnect",
    ecosystem: "multi",
    logo: `${ASSETS_BASE_URL}/assets/wallets/walletconnect.svg`,
    emoji: "🪝",
    homepage: "https://walletconnect.com/",
  },
  {
    id: "rainbow",
    name: "Rainbow",
    category: "app",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/rainbow.svg`,
    emoji: "🌈",
    homepage: "https://rainbow.me/",
    deepLink: (url) => formatDeepLink("rainbow", url) ?? "",
    detectFlags: ["isRainbow"],
  },
  {
    id: "phantom-evm",
    name: "Phantom (EVM)",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/phantom.svg`,
    emoji: "👻",
    homepage: "https://phantom.app/",
    detectFlags: ["isPhantom"],
  },
  {
    id: "phantom-solana",
    name: "Phantom (Solana)",
    category: "injected",
    ecosystem: "solana",
    logo: `${ASSETS_BASE_URL}/assets/wallets/phantom.svg`,
    emoji: "👻",
    homepage: "https://phantom.app/",
    android: "https://play.google.com/store/apps/details?id=app.phantom",
    ios: "https://apps.apple.com/app/phantom-crypto-wallet/id1598432977",
    deepLink: (url) => `phantom://browse/${encodeURIComponent(url)}`,
  },
  {
    id: "solflare",
    name: "Solflare",
    category: "injected",
    ecosystem: "solana",
    logo: `${ASSETS_BASE_URL}/assets/wallets/solflare-logo.svg`,
    emoji: "☀️",
    homepage: "https://solflare.com/",
    deepLink: (url) => `solflare://ul/v1/browse/${encodeURIComponent(url)}`,
  },
  {
    id: "backpack",
    name: "Backpack",
    category: "injected",
    ecosystem: "solana",
    logo: `${ASSETS_BASE_URL}/assets/wallets/backpack-logo.svg`,
    emoji: "🎒",
    homepage: "https://backpack.app/",
  },
  {
    id: "rabby",
    name: "Rabby",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/rabby.svg`,
    emoji: "🐰",
    homepage: "https://rabby.io/",
    chromeWebStore:
      "https://chromewebstore.google.com/detail/rabby/acmacodkjbdgmoleebolmdjonilkdbch",
    detectFlags: ["isRabby"],
  },
  {
    id: "brave",
    name: "Brave Wallet",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/brave.svg`,
    emoji: "🦁",
    homepage: "https://brave.com/wallet/",
    detectFlags: ["isBraveWallet"],
  },
  {
    id: "okx",
    name: "OKX",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/okx.svg`,
    emoji: "⬛",
    homepage: "https://www.okx.com/web3",
    detectFlags: ["isOkxWallet"],
  },
  {
    id: "zerion",
    name: "Zerion",
    category: "app",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/zerion.png`,
    emoji: "🧿",
    homepage: "https://zerion.io/wallet/",
  },
  {
    id: "taho",
    name: "Taho",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/taho.png`,
    emoji: "🟪",
    homepage: "https://taho.xyz/",
    detectFlags: ["isTally", "isTallyWallet", "isTahoWallet"],
  },
  {
    id: "trust",
    name: "Trust Wallet",
    category: "app",
    ecosystem: "multi",
    logo: `${ASSETS_BASE_URL}/assets/wallets/trust.svg`,
    emoji: "🛡️",
    homepage: "https://trustwallet.com/",
    detectFlags: ["isTrustWallet"],
  },
  {
    id: "bitget",
    name: "Bitget Wallet",
    category: "injected",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/bitget.svg`,
    emoji: "🟩",
    homepage: "https://web3.bitget.com/",
    detectFlags: ["isBitGetWallet"],
  },
  {
    id: "safe",
    name: "Safe",
    category: "app",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/safe.svg`,
    emoji: "🟩",
    homepage: "https://safe.global/",
  },
  {
    id: "kucoin",
    name: "KuCoin Wallet",
    category: "app",
    ecosystem: "evm",
    logo: `${ASSETS_BASE_URL}/assets/wallets/kucoin.svg`,
    emoji: "🟦",
    homepage: "https://www.kucoin.com/",
  },
];
